name: Cleanup Artifacts

on:
  schedule:
    # Run weekly on Sunday at 1:00 AM
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const now = new Date();
            const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
            
            for (const artifact of response.data.artifacts) {
              const createdAt = new Date(artifact.created_at);
              if (createdAt < twoWeeksAgo) {
                console.log(`Deleting artifact ${artifact.name} (ID: ${artifact.id}) created at ${artifact.created_at}`);
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
              }
            }